### PR TITLE
Demo for present

### LINKED ISSUE #22: [Feature 1.2] Viewing a List of Chats
This feature pulls up the GUI of the list of active chats.

### LINKED ISSUE #50: Issue#50 Creating the OpenChat use case.
Calls the presenter to open an chat from the ChatList.

### PR DESCRIPTION
**Pull request by EricYH2134**
What is added: the homepage, and connecting ChatList, Chat, and Homepage UI's together

What the code does: the UI is connected with homepage, ChatList, and Chat and all use cases work

Motivation behind it (what is accomplished): for demo 

What testing have you done? test cases and testing the buttons on the UI to see if it works

This is both mine and Rubin's pull request as we merged our branches into this one

### CODE REVIEW

**Review by PotatoRations — APPROVED** [review]
Good use of clean architecture, I also see that you have moved around some files to improve the organisation of the project. There are some unused inputs (java.util.date in ChatController), which should be removed. Also I'm not sure if we need test cases for the new use cases for the home screen, but that might be a good idea to add also.

**Comment by EricYH2134** [comment]
This is a combination of Rubin's and my code as we merged our branches together for this branch to connect our UI's and workflows. This is both mine and Rubin's pull request

**Review by rryt000 — APPROVED** [review]
This pull request includes the addition of the ChatView, ChatListView and other elements of the UI. It also connects the previously unconnected UIs together. JavaDocs need to be added, and I will work on those later. Great step in the right direction.

**Review by angelalbero — APPROVED** [review]
Everything looks good, and thank you for getting started on refactoring. Now we should all add our classes to the respective packages. I don't notice any violations of Clean Architecture or SOLID principles, so I think this is good to be merged to main.

**Pull request merged**
