### PR TITLE
Change textfield to password field

### PR DESCRIPTION
**Pull request by EricYH2134**
What is added: change textfield in login screen to password field

What the code does: makes sure password can't be seen when typed in

Motivation behind it (what is accomplished): to addresss feedback that password can be seen

What testing have you done? Manual testing that it works

### CODE REVIEW

**Review by angelalbero — APPROVED** [review]
This is good, keeping safety in mind for the implementation!

**Review by PotatoRations — APPROVED** [review]
Looks good, fixes a pretty significant bug and improves accessibility of software. Code does not contain javadocs. These should be added

**Review by rryt000 — APPROVED** [review]
Looks good, hides the password so a feature that is needed. Good to go.

**Review by nik-uoft — APPROVED** [review]
Awesome work! Thank you for adjusting this per the feedback from the project presentation.

**Pull request merged**
