### PR TITLE
Feed use cases / UI / persistence 

### LINKED ISSUE #19: [Feature 7.4] Feed Persistance
Implement feed persistence using FeedGateway and FeedRepository

### PR DESCRIPTION
**Pull request by angelalbero**
What is added:
Use cases for liking code snippets, obtaining the current code snippet, and going to the next code snippet ( and related classes such as input/output models & boundaries and presenters & controllers). It also adds a basic UI for the detailed feed, and some unit tests for NextCodeSnippet and CurrentCodeSnippet.

What the code does:
It allows the program to display and advance a feed, and it allows the program to create a match between two users as well. 

Motivation behind it (what is accomplished):
The motivation was to allow users to interact with others by liking code snippets, and that is what this pull request implements.

What testing have you done?
I tested two of my use cases, the NextCodeSnippet and the CurrentCodeSnippet.

### CODE REVIEW

**Review by PotatoRations — DISMISSED** [review]
There's a lot of files to review here, just remember to have javadoc comments for your public methods that aren't getters/setters.

**Comment by PotatoRations** [comment]
Also, it might be an issue that there's so many files in this PR, but it should be okay since a lot of these files are in other PRs. We'll just have to merge those first since Main is so far behind right now

**Review by PotatoRations — DISMISSED** [review]
Good use of Clean architecture. Pull request includes code for Repository, Use cases, and are implemented correctly as far as I can tell. Please include Javadocs for you classes and public methods. Also it might not be a good practice to include test images in your PR (testPicture.jpeg). However this can be removed later. Also please write test cases for your use cases in the future. Good work!

**Review by nik-uoft — DISMISSED** [review]
I've looked through the code and it looks great, and I can't find any problems with it. The view, use cases, and business logic are all implemented correctly as far as I can tell.

**Comment by PotatoRations** [comment]
My previous approval comment still stands, although good use of refactoring old code to get things to work smoother. If possible, could you add a comment that follows the pull request template? I feel like a lot of our older pull requests could still use some improving on how descriptive they are

**Review by PotatoRations — DISMISSED** [review]

**Review by PotatoRations — APPROVED** [review]
That was a lot of work resolving that merge conflict, good work! Good use of clean architecture principals. Also good use of the Observer design pattern in your view and view model. Also good job adding tests to your use cases, although it won't hurt to add more. As with always, please add javadocs, and also it might be bad practice to include test files just as jpeg or json in the production.

**Review by EricYH2134 — APPROVED** [review]
Seems good. Follows clean architecture. Need JavaDoc

**Review by nik-uoft — APPROVED** [review]
LGTM

**Pull request merged**
