### PR TITLE
feat: init CodeSnippet

### LINKED ISSUE #33: [Feature 3.3] Initialize CodeSnippet entities

### PR DESCRIPTION
**Pull request by nik-uoft**
This MR adds the initial entity schema for CodeSnippet

### CODE REVIEW

**Review by PotatoRations — DISMISSED** [review]

**Review by EricYH2134 — CHANGES_REQUESTED** [review]
I believe that a ; is missing on line 7 of CodeSnippetFactory

**Review by EricYH2134 — APPROVED** [review]
Nevermind, ; is added now

**Review by PotatoRations — APPROVED** [review]

**Comment by PotatoRations** [comment]
I'm going to force a commit. I need some of these classes for my classes, and I don't think anyone else is going to review these. We might want to consider reducing the reviews needed to maybe 1 or 2 if possible.

**Comment by PotatoRations** [comment]
Actually, I'll just wait for tomorrow. I don't want to be held responsible for anything weird happening.

**Review by angelalbero — APPROVED** [review]

**Pull request merged**
