### PR TITLE
Repository for users

### PR DESCRIPTION
**Pull request by seetethan**
Repository for users

### CODE REVIEW

**Comment by EricYH2134** [comment]
Will need more of your use case before I can approve

**Comment by PotatoRations** [comment]
The Github Classsroom autograding did not pass. I reviewed it to try to see why. Your commit did not include the UserRepoRequestModel class, and thus the autograder crashed. Please include this class in your commits. You can do this by right clicking on the file on the left, Git -> Add. Then committing and pushing to your branch. 

Also, please improve your Javadocs. There should be one for the class as a whole, as well as each public method. Parameters of the methods should also be included in your javadoc with @param as well as a description after it. This can be done later, however I cannot approve your PR without it passing the autograder.

**Review by PotatoRations — APPROVED** [review]
Good use of clean architechture, Use cases, entities, and repositories are all there and implemented correctly to my knowledge. As with before, please add test cases and Javadoc comments. But these can be done later. I'm not 100% sure you need setters for a request model, since the values for the request model would all be added at creation. Also your UserRepoRequestModel constructor has a lot of parameters. I'm not 100% sure how this could be fixed or if it is really that big of an issue, but its something to keep in mind for now.

**Review by EricYH2134 — CHANGES_REQUESTED** [review]
Currently, the UserRepository's delete function doesn't do anything really, so if it is possible to add a boolean isDeleted in the User entity and also the UserRepoRequestModel with getters and setters, then you can have your UserRepository's delete function set isDeleted as true before resaving it. Adding the new variable will also mean changing the constructor and wherever you call that constructor to accomodate for the new variable.

Otherwise, it follows clean architecture fairly well, and we need JavaDoc and test cases as well, but that can be done a bit later

**Review by angelalbero — DISMISSED** [review]
Everything looks good to me! Seems to follow clean architecture closely, and I don't notice any bad code smells. As pointed out by Eric and Aerin, there's the tests missing but that can be done later. Also, if I remember correctly, I think we agreed on having JavaDoc for setters and getters as well, so you might want to add those to the methods. Other than that, everything seems fine.

**Review by PotatoRations — CHANGES_REQUESTED** [review]
There's no way to request user information from your repository, please add a method in the gateway for retrieving user data from the repository.

**Review by PotatoRations — APPROVED** [review]
Good use of clean architechture elements (repository, use cases, entities). Dependency inversion is also used properly. As with before, please include test cases for your use cases, as well as javadocs for you classes and public methods. Also technically by interface segregation, you might want to split up your userRepoGateway into multiple smaller gateways for the needs of each specific use case, but I also feel that that would probably be unnecessarily complicated for this project.

**Review by EricYH2134 — APPROVED** [review]
Good clean architecture. However, you should change the "listOfChatIds" names to "mapOfChatToOtherUser" or something along those lines, because even though they are all maps now, they are still the old name of 'list' rather than 'map'. You still need JavaDoc on public methods

**Review by angelalbero — APPROVED** [review]
The code seems to follow SOLID principles and clean architecture closely. I only notice some JavaDocs missing and the unit tests. Other than that, it looks good to be merged.

**Pull request merged**
