### PR TITLE
RegisterUI

### PR DESCRIPTION
**Pull request by seetethan**
What is added: UI for user registration

What the code does: Adds a register screen

### CODE REVIEW

**Review by EricYH2134 — DISMISSED** [review]
Add a presenter to account for possible errors in user registration, also, the controller has a lot of input boundaries not being used, so delete them from the controller if not needed. I'll approve because we need this

**Review by angelalbero — DISMISSED** [review]
Looks good to be merged so that we can put it together for the presentation demo.

**Review by EricYH2134 — APPROVED** [review]
Same comment as before

**Review by angelalbero — APPROVED** [review]
Looks good to be merged so that we can put it together for the presentation demo.

**Comment by nik-uoft** [comment]
Reviewed the code, LGTM!

**Review by nik-uoft — APPROVED** [review]

**Pull request merged**
