### PR TITLE
Fix next snippet bug and UI

### PR DESCRIPTION
**Pull request by angelalbero**
What is added: 
I fixed a bug that there was in my NextSnippet Use Case. I also changed some import statements that were causing trouble. I edited my View, and finished refactoring my code to put it in the correct packages. 

What the code does:
Allows the NextSnippet to work properly now. 

Motivation behind it (what is accomplished):
The DetailedView can work now. With the prior version of the use case it would crash. 

What testing have you done?
No testing has been done as it was small changes to the UI and the use case.

### CODE REVIEW

**Review by EricYH2134 — DISMISSED** [review]
Seems good. Good refactoring to match the way we organized code

**Review by nik-uoft — DISMISSED** [review]
Reviewed the code. LGTM!

**Review by EricYH2134 — APPROVED** [review]
Same comment as before

**Review by nik-uoft — APPROVED** [review]
LGTM

**Review by rryt000 — APPROVED** [review]
Good refactoring, follows clean architecture.

**Review by PotatoRations — APPROVED** [review]
Good work shifting some files around
Also good work with removing some unused methods, good removal of code smells. 
Also passed autograding, so I will approve. Please add javadocs and test cases please

**Pull request merged**
