### PR TITLE
fix: refactor imports

### PR DESCRIPTION
**Pull request by nik-uoft**
What is added:
Refactor imports 

What the code does:
Minor imports fixes to resolve syntax errors caused by a previous PR

Motivation behind it (what is accomplished)
The program does not compile without the fixes. So this fix is essential 

What testing have you done?
The app runs with theses fixes
Fixes also pass github autograding

### CODE REVIEW

**Review by angelalbero — DISMISSED** [review]
Looks good, thank you for fixing the import statement conflicts!

**Review by PotatoRations — DISMISSED** [review]
Good work fixing errors in the code caused by a refactoring in a previous PR. I'm not sure if this counts as refactoring since the code did not run without it, but good work nonetheless

**Review by seetethan — DISMISSED** [review]
Error Fixing code looks good. Good work!

**Review by angelalbero — APPROVED** [review]
Looks good, thank you for fixing the import statement conflicts!

**Review by PotatoRations — APPROVED** [review]
Please refer to my previous approve comment

**Review by EricYH2134 — APPROVED** [review]
Good fixes

**Pull request merged**
