### PR TITLE
feat: add use cases and data persistence for CodeSnippet

### LINKED ISSUE #25: [Feature 3.2] Add use cases and data persistence for CodeSnippet

### PR DESCRIPTION
**Pull request by nik-uoft**
This MR adds use cases and data persistence for CodeSnippet

### CODE REVIEW

**Review by EricYH2134 — CHANGES_REQUESTED** [review]
Missing return statement in CodeSnippetInteractor's create method is causing the autograding to fail. Also, you have the interface for CodeSnippetFactory, but what is implementing it? It should have a factory class implementing it, or it shouldn't be an interface. I'm also not sure if the Interactor should have all three methods, or if it should be split into three use cases. It otherwise seems fine in terms of clean architecture, and now you just need to implement some of the methods that you haven't done yet

**Review by angelalbero — CHANGES_REQUESTED** [review]
The CodeSnippetResponseModel currently doesn't have a variable for the userId of the user to whom the codeSnippet belongs. Could that be added? I see that it is stored in the repository because it is present in the CodeSnippetRequestModel, but we can't retrieve it unless we have a variable for it in the CodeSnippetResponseModel right?

**Comment by nik-uoft** [comment]
@angelalbero added missing getId to CodeSnippetResponseModel

**Review by EricYH2134 — APPROVED** [review]
Looks good. Now you need test cases for your use cases and JavaDoc for your public methods

**Review by PotatoRations — APPROVED** [review]
Pull request follows the clean architecture structure (Contains entities, use cases, and repository). Dependency inversion is also correctly done in the use case. The only issue I can currently find is of Javadoc and tests. Please add Javadocs to your public methods and your classes later. And please add tests as well later. 

I will approve as these issues can be solved later when refactoring

**Review by angelalbero — APPROVED** [review]
Looks good, thanks for adding the userId variable with the getter.

**Pull request merged**
