### PR TITLE
Update README.md

### LINKED ISSUE #65: Update Read me
Update read me with design patterns used, use of clean architecture, how to run the code, and screenshots of stuff that we have not yet connected or fully finished that we would like to connect if we had the time. Talk about each feature

### PR DESCRIPTION
**Pull request by angelalbero**
What is added: fixed issues regarding imports caused by the last pull request

What the code does: swaps around some

Motivation behind it (what is accomplished)
needed to fix issues

What testing have you done?

### CODE REVIEW

**Review by PotatoRations — DISMISSED** [review]
Looks good, not much to review since this is not code

**Review by rryt000 — APPROVED** [review]
Creating the ReadME as needed, so approved.

**Review by EricYH2134 — APPROVED** [review]
Looks good for our ReadMe

**Review by nik-uoft — APPROVED** [review]
LGTM

**Pull request merged**
