### PR TITLE
12 add feed entities part 1 entities only

### LINKED ISSUE #12: [Feature 7.0] Add Feed Entities
Add entities required for feed:

Feed, FeedFactory, CodeSnippet

### PR DESCRIPTION
**Pull request by PotatoRations**
Branch containing only feed entities. I will create another PR that include only the CreateFeedUseCase.

Branch contains Feed, Tag, FeedFactory, TagFactory, and Taggable interfaces

### CODE REVIEW

**Review by EricYH2134 — CHANGES_REQUESTED** [review]
This is adding the .idea and gradle stuff. Please remove it. It otherwise seems fine

**Comment by PotatoRations** [comment]
Ah, yeah I reverted some commits to get only the finished entities. It should be fixed now

**Review by EricYH2134 — DISMISSED** [review]
Seems good. You should add some JavaDoc later for your public methods that aren't getters and setters

**Review by angelalbero — DISMISSED** [review]

**Review by EricYH2134 — DISMISSED** [review]
We need JavaDoc for your public methods, but that can be done later. Good use of the Iteration design pattern to compare code snippets. Follows clean architecture and SOLID for this layer

**Review by angelalbero — APPROVED** [review]
Looks good, thanks for adding the userId variable and its getter/setter!

**Review by EricYH2134 — APPROVED** [review]
We need JavaDoc for your public methods, but that can be done later. Good use of the Iteration design pattern to compare code snippets. Seems good for clean architecture and SOLID for this layer

**Review by rryt000 — APPROVED** [review]
Looks good, make sure to add Javadocs and think about testing your methods if possible.

**Pull request merged**
