### PR TITLE
Created the ChatDeletion UseCase and persistence.

### PR DESCRIPTION
**Pull request by rryt000**

### CODE REVIEW

**Review by EricYH2134 — APPROVED** [review]
Your delete chat use case looks good, and the files you submit follow clean architecture and SOLID, with use case being injected with the repository gateway, and the use case using the gateway which is an interface to save persistence. Furthermore, good job on using JavaDoc to tell us what the public functions do (other than getters and setters). We will have to combine our repository files and the repo request model files later as we worked on them together, and they overlap in quite a few areas. We will also likely have to reorganize our files as well after merging. You need to add test cases for your use case, and start working on your UI, controller, and presenter classes for your part

**Review by PotatoRations — APPROVED** [review]
Overall, the code looks okay, for the most part it follows clean architecture principles. I have found a few potential issues:
1. (this is a minor issue), the naming conventions of the classes such as the use case and the gateway/repository are not consistent with others on the team. This is not really significant as we have not really agreed on a naming convention yet and this can easily be refactored and fixed. 
2. I'm not sure if we need a specific repository for Chat deletion. Likely this can be done through a single chat repository that just handles saving chats for all chat-related use cases. 

I think it's still okay to approve this however, since these changes can be fixed after merging  when we refactor the code

**Comment by seetethan** [comment]
Follows SOLID design principles, follows other clean architecture principles (layers, use of gateways, single use.). Plenty of comments/javadoc which is helpful for understanding how the code works. Adding test cases will help in verifying correctness before merging.

**Review by seetethan — APPROVED** [review]

**Review by angelalbero — APPROVED** [review]
I think everything looks great regarding SOLID principles, especially the interface segregation principle. I think the code also looks great (other than the bits that are still pseudocode, but I think it’s good that you’ve already started thinking of what steps to take next). Remember to write test units for your use cases, and other than that, everything looks great. Lastly, regarding clean architecture, I don’t see any violations (such as dependencies going the wrong direction), so I think everything looks great!

**Pull request merged**
